all:
  children:
    group1:
      hosts:
        ct-ubuntu-1:
          ansible_host: 192.168.9.51
#          ansible_user: root
    group2:
      hosts:
        ct-ubuntu-2:
          ansible_host: 192.168.9.52
      
 #         ansible_user: root
  #        ansible_ssh_private_key_file: /etc/ssh/ct2
